# Generated by Django 3.1 on 2020-08-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200813_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
